### ISSUE TITLE
Is there a way to make server work without pasv

### ISSUE THREAD

**Issue by arthurvaverko** [FubarDevelopment/FtpServer#66]
Im having trouble running docker image with mapping of pasv ports. 
If you do 
docker run -p 3000-4000:3000-400 -p 21:21 myFTPimage

The command will hand for a while and then fail 
As the docker engine will not be able to create so many port mapping .. 

So I figured there must be a way to configure the server to work without pasv. Is there ?

**Comment by fubar-coder** [comment]
Two solutions:

- You can limit the `PASV` port range to use in the server. (option `s` or `pasv` in the server sample). This will actually limit the number of parallel data connections.
- `PASV` is always initiated by the client. You have to choose "active" data connections instead of "passive" (usually the default) in your client.

Be aware that ACTIVE data connections usually only work when you're in the same network as the FTP server, because the FTP server actively creates a TCP connection to the client. So, the client has to listen at a selected port and the firewall (on the client and/or server) must not get in the way.
