### ISSUE TITLE
Provide a way to specifiy a list of allowed ports for passive data connections.

### ISSUE THREAD

**Issue by fubar-coder** [FubarDevelopment/FtpServer#8]
This seems to be required when the FTP server is used as Azure service with public/accessible end points.

**Comment by fubar-coder** [comment]
There is a Gist with changes made by Guillaume Pelletier (dotvision.com): https://gist.github.com/fubar-coder/32a1a6d859d12a9961e1a7e897a27900

**Comment by chaseaucoin** [comment]
Okay so this and #43 were blocking my ability to deploy via containers but I have resolved this as well. Looks like the way PASV is handled has shifted somewhat since the proposed GIST

Not sure how you want to pass the pasv port array to the handler but I did this hard coded just to get me by for right now.

`public class PasvCommandHandler : FtpCommandHandler
    {
        static ConcurrentQueue<int> _portQueue = new ConcurrentQueue<int>(Enumerable.Range(8000, 30));
}`
            
            int dequeuedPort;
            while (!_portQueue.TryDequeue(out dequeuedPort)) { }
            
            int port;

            var isEpsv = string.Equals(command.Name, "EPSV", StringComparison.OrdinalIgnoreCase);
            if (isEpsv)
            {
                if (string.IsNullOrEmpty(command.Argument) || string.Equals(command.Argument, "ALL", StringComparison.OrdinalIgnoreCase))
                {
                    port = dequeuedPort;
                }
                else
                {
                    port = Convert.ToInt32(command.Argument, 10);
                }
            }
            else
            {
                port = dequeuedPort;
            }
`
